language: rust
rust: nightly-2018-12-06
os:
  - linux
  - osx

matrix:
  include:
    - env: JOB=rustfmt
      os: linux
      install:
        rustup component add rustfmt
      script:
        cargo fmt --all -- --check

before_install:
- |
    set -e
    # fail loudly when force-pushed
    MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
    # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
    if ! echo ${MODIFIED_FILES} | grep -qvE '(\.md$)|(^docs)/'; then
      echo "Only docs were updated, stopping build process."
      exit
    fi

install:
  - bash ./scripts/install.sh

script:
  - make
  - cargo build --features use_semihosting
  - make bloat

cache:
  cargo: true

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r ${HOME}/.cargo

before_deploy:
  - git config --local user.name "Andreas Heider"
  - git config --local user.email "andreas@heider.io"
  - git tag "$(date +'%Y-%m-%d')-$TRAVIS_BUILD_NUMBER-${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}-$(git log --format=%h -1)"

branches:
  except:
    - /^\d+-\d+-\d+-.*/

deploy:
  on:
    condition: "${TRAVIS_OS_NAME} == 'linux'"
  provider: releases
  api_key:
    secure: "hSYihrRGZNCwdZQkmQoIlPHsUYewhaKJpui45vR8vYyUg3S1l2lGPTkIffA5VILZ/ozZiB/uynYNJlRxGG0+ZyZzZRsHEUS8dY/GpYHEjEvAMVJE/JkG4gKcXD7q9Tvwdik7huzzilAjbw4wAdkY3IiIXMQhpoPc3Dele7RTUdilpWzi3UtZyvrs0k0f2Gfovu2yXkkpXsC5Pwm17Pe0sGa+ilB1OlZ1lWrCA8zHtSBH+V4IztgKf1c7kPr5nWG8uLvMYmlun9l0/ahymh8SJyAOm0EHkhfZYCX/EG2JG0NYTAQJ88Ags+xbDWaoGtNo+R+yzAUG5PfcaAXKAj6I10Rsg6/ckCSFlliDtKi6qrV2+YmbnXchy97PqlJM0zZKWzpvncXlhJ46O3DoMm4L5btj9hCahagqfJpNEZ8olnLlVhzFTGBGPyQVvMudPXcFSDMHLGejNPxua5lq+LOlEH2gSezDc9Qzm96tpiYu1lKt8Ousz7lAin9BS/7+ES7W2Fx2I5cQ7965kxARGzyhHCQXOkGPrj/M6tW6qlec3AS6yM+oxTvQnKJPhbERaClio46NukUbIG4CZ+Hwi2jtb8tLQ6g1J7fbA2ac3faiw3MmZDNmGSW0DGaOUkv/EGuoHc5sTNR6fITYTbkH2g24G1iYnsg3kLNiseSkODJxySo="
  file:
    - "target/thumbv7m-none-eabi/release/anne-key"
    - "anne-key.dfu"
  skip_cleanup: true
